# Project 1

## Features of Dataset
**Covariates:**
* gpa
* gre

**Predictor:**
* prestige

**Outcome:**
* admit

## Problem Statement
Determine which applicants will be admitted to UCLA's graduate school using admissions data (GRE, GPA and alma mater).

### Data Dictionary

Variable | Description
---------|------------
gpa | Grade Point Average
gre | Graduate Record Examination
prestige | Rank of an applicant's alma mater
admit | admission indicator

Variable Notes:
* GPA: 4 point scale
* GRE: max score of 800
* prestige: 1 is the highest, 4 the lowest
* admit: 1 = admitted, 0 = not admitted

## Risks and Assumptions
* assumes data is from the same time period
* data does not account for demographic data including gender or race which could have impact on admittance rate
* smaller dataset may make it harder to make an association

## Hypothesis
Applicants will be more likely to admitted to UCLA if their alma mater is ranked 1 rather than 2, 3, or 4.

## Exploratory Analysis
1. Analyze data using summary statistics (e.g. mean, median, etc) and to see if any rows are missing data (rows returning NaN)
+ remove any rows with incomplete or missing data
* Plot a frequency distribution of admitted students by prestige
- identify any outliers

In [27]:
import pandas as pd
import matplotlib as mp

df = pd.read_csv("admissions.csv")

df

     admit    gre   gpa  prestige
0        0  380.0  3.61       3.0
1        1  660.0  3.67       3.0
2        1  800.0  4.00       1.0
3        1  640.0  3.19       4.0
4        0  520.0  2.93       4.0
5        1  760.0  3.00       2.0
6        1  560.0  2.98       1.0
7        0  400.0  3.08       2.0
8        1  540.0  3.39       3.0
9        0  700.0  3.92       2.0
10       0  800.0  4.00       4.0
11       0  440.0  3.22       1.0
12       1  760.0  4.00       1.0
13       0  700.0  3.08       2.0
14       1  700.0  4.00       1.0
15       0  480.0  3.44       3.0
16       0  780.0  3.87       4.0
17       0  360.0  2.56       3.0
18       0  800.0  3.75       2.0
19       1  540.0  3.81       1.0
20       0  500.0  3.17       3.0
21       1  660.0  3.63       2.0
22       0  600.0  2.82       4.0
23       0  680.0  3.19       4.0
24       1  760.0  3.35       2.0
25       1  800.0  3.66       1.0
26       1  620.0  3.61       1.0
27       1  520.0  3.74       4.0
28       1  780.0  3.22       2.0
29       0  520.0  3.29       1.0
..     ...    ...   ...       ...
370      1  540.0  3.77       2.0
371      1  680.0  3.76       3.0
372      1  680.0  2.42       1.0
373      1  620.0  3.37       1.0
374      0  560.0  3.78       2.0
375      0  560.0  3.49       4.0
376      0  620.0  3.63       2.0
377      1  800.0  4.00       2.0
378      0  640.0  3.12       3.0
379      0  540.0  2.70       2.0
380      0  700.0  3.65       2.0
381      1  540.0  3.49       2.0
382      0  540.0  3.51       2.0
383      0  660.0  4.00       1.0
384      1  480.0  2.62       2.0
385      0  420.0  3.02       1.0
386      1  740.0  3.86       2.0
387      0  580.0  3.36       2.0
388      0  640.0  3.17       2.0
389      0  640.0  3.51       2.0
390      1  800.0  3.05       2.0
391      1  660.0  3.88       2.0
392      1  600.0  3.38       3.0
393      1  620.0  3.75       2.0
394      1  460.0  3.99       3.0
395      0  620.0  4.00       2.0
396      0  560.0  3.04       3.0
397      0  460.0  2.63       2.0
398      0  700.0  3.65       2.0
399      0  600.0  3.89       3.0

[400 rows x 4 columns]

In [28]:
df.describe()

            admit         gre        gpa    prestige
count  400.000000  398.000000  398.00000  399.000000
mean     0.317500  588.040201    3.39093    2.486216
std      0.466087  115.628513    0.38063    0.945333
min      0.000000  220.000000    2.26000    1.000000
25%      0.000000  520.000000    3.13000    2.000000
50%      0.000000  580.000000    3.39500    2.000000
75%      1.000000  660.000000    3.67000    3.000000
max      1.000000  800.000000    4.00000    4.000000